package fi.foyt.fni.persistence.model.users;

public enum Permission {
	
	NONE,
	
	MATERIAL_ACCESS,
	MATERIAL_MODIFY,
	MATERIAL_DELETE,

	PROFILE_UPDATE,
	
	FORUM_POST_CREATE,
	FORUM_TOPIC_CREATE,
	FORUM_POST_MODIFY,
  FORUM_TOPIC_MODIFY,
  FORUM_POST_MODERATE,
  FORUM_TOPIC_MODERATE,
  
  ILLUSION_GROUP_ACCESS,
  
	GAMELIBRARY_VIEW_ORDER,
	GAMELIBRARY_MANAGE_ORDERS,
	GAMELIBRARY_MANAGE_PUBLICATIONS,
	
	SYSTEM_ADMINISTRATION
}
