package fi.foyt.fni.persistence.model.system;

public enum SystemSettingKey {
	
	/* System Wide */
	
	DEFAULT_LOCALE,
	DEFAULT_LANGUAGE,
	SYSTEM_USER_EMAIL,
	SYSTEM_MAILER_NAME,
	SYSTEM_MAILER_MAIL,
	PIWIK_URL,
  PIWIK_SITEID,
	USERVOICE_CLIENT_KEY,

	/* Guest */
	
	GUEST_USERNAME,
	GUEST_PASSWORD,
	
	/* Google */
	
	GOOGLE_APIKEY,
	GOOGLE_APISECRET,
	GOOGLE_CALLBACKURL,
	
	/* Yahoo */
	
	YAHOO_APIKEY,
	YAHOO_APISECRET,
	YAHOO_CALLBACKURL,
	
	/* Facebook */ 
	
	FACEBOOK_APIKEY,
	FACEBOOK_APISECRET,
	FACEBOOK_CALLBACKURL,
	
	/* Dropbox */
	
	DROPBOX_APIKEY,
	DROPBOX_APISECRET,
	DROPBOX_CALLBACKURL,
	DROPBOX_ROOT,
	
	/* Ubuntu One */
	
	UBUNTUONE_APIKEY,
	UBUNTUONE_APISECRET,
	UBUNTUONE_CALLBACKURL,

	/* Game Library specific */
	
	GAMELIBRARY_PUBLICATION_FORUM_ID,
	GAMELIBRARY_ORDERMAILER_NAME,
	GAMELIBRARY_ORDERMAILER_MAIL,
	GAMELIBRARY_SHOP_OWNER_NAME,
  GAMELIBRARY_SHOP_OWNER_MAIL,
	
  /* Paytrail */
  
  PAYTRAIL_MERCHANT_ID,
  PAYTRAIL_MERCHANT_SECRET,
  
  /* Chat */
  
  CHAT_DOMAIN,
  CHAT_MUC_HOST,
  CHAT_BOSH_SERVICE,
  CHAT_CREDENTIAL_SALT,
  CHAT_CREDENTIAL_PASSPHRASE,
  CHAT_CREDENTIAL_ITERATIONS,
  CHAT_ADMIN_JID,
  CHAT_ADMIN_PASSWORD,
  CHAT_BOT_JID
}

