package fi.foyt.fni.persistence.model.system;

public enum SystemSettingKey {
	
	/* System Wide */
	
	DEFAULT_LOCALE,
	SYSTEM_USER_EMAIL,
	SYSTEM_MAILER_NAME,
	SYSTEM_MAILER_MAIL,
	PIWIK_URL,
	USERVOICE_CLIENT_KEY,

	/* Guest */
	
	GUEST_USERNAME,
	GUEST_PASSWORD,
	
	/* Google */
	
	GOOGLE_APIKEY,
	GOOGLE_APISECRET,
	GOOGLE_CALLBACKURL,
	
	/* Yahoo */
	
	YAHOO_APIKEY,
	YAHOO_APISECRET,
	YAHOO_CALLBACKURL,
	
	/* Facebook */ 
	
	FACEBOOK_APIKEY,
	FACEBOOK_APISECRET,
	FACEBOOK_CALLBACKURL,
	
	/* Dropbox */
	
	DROPBOX_APIKEY,
	DROPBOX_APISECRET,
	DROPBOX_CALLBACKURL,
	DROPBOX_ROOT,
	
	/* Ubuntu One */
	
	UBUNTUONE_APIKEY,
	UBUNTUONE_APISECRET,
	UBUNTUONE_CALLBACKURL,

	/* Game Library specific */
	
	GAMELIBRARY_PUBLICATION_FORUM_ID,
	GAMELIBRARY_ORDERMAILER_NAME,
	GAMELIBRARY_ORDERMAILER_MAIL,
	GAMELIBRARY_SHOP_OWNER_NAME,
  GAMELIBRARY_SHOP_OWNER_MAIL
	
}

