insert into   
  Material (id, created, modified, publicity, title, type, urlName, creator_id, modifier_id, parentFolder_id)
values 
  (123, PARSEDATETIME('1 1 2010', 'd M yyyy'), PARSEDATETIME('1 1 2010', 'd M yyyy'), 'PRIVATE', 'Book Design', 'BOOK_DESIGN', 'book-design', 2, 2, null),
  (124, PARSEDATETIME('1 1 2010', 'd M yyyy'), PARSEDATETIME('1 1 2010', 'd M yyyy'), 'PRIVATE', 'Book Design in Folder', 'BOOK_DESIGN', 'book-design_in_folder', 2, 2, 1),
  (125, PARSEDATETIME('1 1 2010', 'd M yyyy'), PARSEDATETIME('1 1 2010', 'd M yyyy'), 'PRIVATE', 'Book Design in Subfolder', 'BOOK_DESIGN', 'book-design_in_subfolder', 2, 2, 2);
  
INSERT INTO BookDesign (id, data, fonts, styles, pageTypes) VALUES 
  (123, '<section data-page-number="1" class="forge-book-designer-page" data-type-name="Contents" data-type-id="pt-14f4a99f8d8-62338a2f"><header></header><main style="height: calc(100% - 19px);"><h1 style="text-align: center;" class="">&nbsp;Header</h1></main><footer>1</footer></section>', '[{"name":"Tinos","url":"http://fonts.googleapis.com/css?family=Tinos:400,400italic,700,700italic"}]', '[{"name":"Body","selector":"p","rules":{"font-family":"Tinos","font-size":"12pt","margin-top":"14pt","margin-bottom":"14pt","font-variant":"normal","name":"Body"}},{"name":"Header 1","selector":"h1","rules":{"font-family":"PT Serif","font-size":"28pt","margin-top":"18pt","margin-bottom":"18pt","font-weight":"bold","font-variant":"small-caps","name":"Header 1"}},{"name":"Header 2","selector":"h2","rules":{"font-family":"PT Serif","font-size":"24pt","margin-top":"16pt","margin-bottom":"16pt","font-weight":"bold","font-variant":"small-caps","name":"Header 2"}},{"name":"Header 3","selector":"h3","rules":{"font-family":"PT Serif","font-size":"20pt","margin-top":"14pt","margin-bottom":"14pt","font-weight":"bold","name":"Header 3"}},{"name":"Header 4","selector":"h4","rules":{"font-family":"PT Serif","font-size":"18pt","margin-top":"12pt","margin-bottom":"12pt","font-weight":"bold","name":"Header 4"}},{"name":"Header 5","selector":"h5","rules":{"font-family":"PT Serif","font-size":"16pt","margin-top":"10pt","margin-bottom":"10pt","font-weight":"bold","name":"Header 5"}},{"name":"Header 6","selector":"h6","rules":{"font-family":"PT Serif","font-size":"14pt","margin-top":"8pt","margin-bottom":"8pt","font-weight":"bold","name":"Header 6"}},{"name":"Bullet list","selector":"ul","rules":{"font-family":"Tinos","font-size":"12pt","margin-left":"30pt","list-style-type":"disc","name":"Bullet list"}},{"name":"Number list","selector":"ol","rules":{"font-family":"Tinos","font-size":"12pt","margin-left":"30pt","list-style-type":"decimal","name":"Number list"}}]', '[{"id":"pt-14f4a99f8d8-62338a2f","name":"Contents","numberedPage":true,"pageRules":{"background-image":"url()","background-position":"center center","background-size":"","background-repeat":"no-repeat","padding-top":"4em","padding-right":"4em","padding-bottom":"4em","padding-left":"4em","name":"Contents"},"header":{"text":"","rules":{"display":"none","text-align":"center","background-color":"","padding-top":"0pt","padding-right":"0pt","padding-bottom":"0pt","padding-left":"0pt","show":"on","font-family":"PT Serif"}},"footer":{"text":"[[PAGE]]","rules":{"display":"block","text-align":"center"}}}]'), 
  (124, '<section data-page-number="1" class="forge-book-designer-page" data-type-name="Contents" data-type-id="pt-14f4a99f8d8-62338a2f"><header></header><main style="height: calc(100% - 19px);"><h1 style="text-align: center;" class="">&nbsp;Header</h1></main><footer>1</footer></section>', '[{"name":"Tinos","url":"http://fonts.googleapis.com/css?family=Tinos:400,400italic,700,700italic"}]', '[{"name":"Body","selector":"p","rules":{"font-family":"Tinos","font-size":"12pt","margin-top":"14pt","margin-bottom":"14pt","font-variant":"normal","name":"Body"}},{"name":"Header 1","selector":"h1","rules":{"font-family":"PT Serif","font-size":"28pt","margin-top":"18pt","margin-bottom":"18pt","font-weight":"bold","font-variant":"small-caps","name":"Header 1"}},{"name":"Header 2","selector":"h2","rules":{"font-family":"PT Serif","font-size":"24pt","margin-top":"16pt","margin-bottom":"16pt","font-weight":"bold","font-variant":"small-caps","name":"Header 2"}},{"name":"Header 3","selector":"h3","rules":{"font-family":"PT Serif","font-size":"20pt","margin-top":"14pt","margin-bottom":"14pt","font-weight":"bold","name":"Header 3"}},{"name":"Header 4","selector":"h4","rules":{"font-family":"PT Serif","font-size":"18pt","margin-top":"12pt","margin-bottom":"12pt","font-weight":"bold","name":"Header 4"}},{"name":"Header 5","selector":"h5","rules":{"font-family":"PT Serif","font-size":"16pt","margin-top":"10pt","margin-bottom":"10pt","font-weight":"bold","name":"Header 5"}},{"name":"Header 6","selector":"h6","rules":{"font-family":"PT Serif","font-size":"14pt","margin-top":"8pt","margin-bottom":"8pt","font-weight":"bold","name":"Header 6"}},{"name":"Bullet list","selector":"ul","rules":{"font-family":"Tinos","font-size":"12pt","margin-left":"30pt","list-style-type":"disc","name":"Bullet list"}},{"name":"Number list","selector":"ol","rules":{"font-family":"Tinos","font-size":"12pt","margin-left":"30pt","list-style-type":"decimal","name":"Number list"}}]', '[{"id":"pt-14f4a99f8d8-62338a2f","name":"Contents","numberedPage":true,"pageRules":{"background-image":"url()","background-position":"center center","background-size":"","background-repeat":"no-repeat","padding-top":"4em","padding-right":"4em","padding-bottom":"4em","padding-left":"4em","name":"Contents"},"header":{"text":"","rules":{"display":"none","text-align":"center","background-color":"","padding-top":"0pt","padding-right":"0pt","padding-bottom":"0pt","padding-left":"0pt","show":"on","font-family":"PT Serif"}},"footer":{"text":"[[PAGE]]","rules":{"display":"block","text-align":"center"}}}]'), 
  (125, '<section data-page-number="1" class="forge-book-designer-page" data-type-name="Contents" data-type-id="pt-14f4a99f8d8-62338a2f"><header></header><main style="height: calc(100% - 19px);"><h1 style="text-align: center;" class="">&nbsp;Header</h1></main><footer>1</footer></section>', '[{"name":"Tinos","url":"http://fonts.googleapis.com/css?family=Tinos:400,400italic,700,700italic"}]', '[{"name":"Body","selector":"p","rules":{"font-family":"Tinos","font-size":"12pt","margin-top":"14pt","margin-bottom":"14pt","font-variant":"normal","name":"Body"}},{"name":"Header 1","selector":"h1","rules":{"font-family":"PT Serif","font-size":"28pt","margin-top":"18pt","margin-bottom":"18pt","font-weight":"bold","font-variant":"small-caps","name":"Header 1"}},{"name":"Header 2","selector":"h2","rules":{"font-family":"PT Serif","font-size":"24pt","margin-top":"16pt","margin-bottom":"16pt","font-weight":"bold","font-variant":"small-caps","name":"Header 2"}},{"name":"Header 3","selector":"h3","rules":{"font-family":"PT Serif","font-size":"20pt","margin-top":"14pt","margin-bottom":"14pt","font-weight":"bold","name":"Header 3"}},{"name":"Header 4","selector":"h4","rules":{"font-family":"PT Serif","font-size":"18pt","margin-top":"12pt","margin-bottom":"12pt","font-weight":"bold","name":"Header 4"}},{"name":"Header 5","selector":"h5","rules":{"font-family":"PT Serif","font-size":"16pt","margin-top":"10pt","margin-bottom":"10pt","font-weight":"bold","name":"Header 5"}},{"name":"Header 6","selector":"h6","rules":{"font-family":"PT Serif","font-size":"14pt","margin-top":"8pt","margin-bottom":"8pt","font-weight":"bold","name":"Header 6"}},{"name":"Bullet list","selector":"ul","rules":{"font-family":"Tinos","font-size":"12pt","margin-left":"30pt","list-style-type":"disc","name":"Bullet list"}},{"name":"Number list","selector":"ol","rules":{"font-family":"Tinos","font-size":"12pt","margin-left":"30pt","list-style-type":"decimal","name":"Number list"}}]', '[{"id":"pt-14f4a99f8d8-62338a2f","name":"Contents","numberedPage":true,"pageRules":{"background-image":"url()","background-position":"center center","background-size":"","background-repeat":"no-repeat","padding-top":"4em","padding-right":"4em","padding-bottom":"4em","padding-left":"4em","name":"Contents"},"header":{"text":"","rules":{"display":"none","text-align":"center","background-color":"","padding-top":"0pt","padding-right":"0pt","padding-bottom":"0pt","padding-left":"0pt","show":"on","font-family":"PT Serif"}},"footer":{"text":"[[PAGE]]","rules":{"display":"block","text-align":"center"}}}]');
  
insert into   
  MaterialShare (id, role, material_id)
values 
  (1001, 'MAY_EDIT', 123),
  (1002, 'MAY_VIEW', 123);
    
insert into   
  MaterialShareUser (id, user_id)
values 
  (1001, 3),
  (1002, 4);