delete from MaterialView where material_id in (20001, 20000);
delete from IllusionEventGenre where event_id = 1;
delete from IllusionEventParticipant where event_id in (1);
delete from IllusionEventDocument where id = 20001;
delete from Document where id = 20001;
delete from Material where id = 20001;
delete from IllusionEventSetting where event_id in (1);
delete from IllusionEvent where id = 1;
delete from IllusionEventFolder where id = 20000;
delete from Folder where id = 20000;
delete from Material where id = 20000;