package fi.foyt.fni.persistence.model.materials;

public enum MaterialType {
  DOCUMENT,
  IMAGE,
  PDF,
  FILE,
  FOLDER,
  BINARY,
  VECTOR_IMAGE,
  BOOK_DESIGN,
  BOOK_TEMPLATE,
  GOOGLE_DOCUMENT,
  DROPBOX_ROOT_FOLDER,
  DROPBOX_FOLDER,
  DROPBOX_FILE,
  ILLUSION_FOLDER,
  ILLUSION_GROUP_FOLDER,
  ILLUSION_GROUP_DOCUMENT,
  CHARACTER_SHEET
}
