package fi.foyt.fni.persistence.model.materials;

public enum MaterialType {
  DOCUMENT,
  IMAGE,
  PDF,
  FILE,
  FOLDER,
  BINARY,
  VECTOR_IMAGE,
  GOOGLE_DOCUMENT,
  DROPBOX_ROOT_FOLDER,
  DROPBOX_FOLDER,
  DROPBOX_FILE,
  UBUNTU_ONE_ROOT_FOLDER,
  UBUNTU_ONE_FOLDER,
  UBUNTU_ONE_FILE
}
