package fi.foyt.fni.rest.illusion;

public enum OAuthScopes {
  
  ILLUSION_LIST_EVENTS,
  ILLUSION_FIND_EVENT,
  ILLUSION_CREATE_EVENT,
  ILLUSION_UPDATE_EVENT,
  ILLUSION_DELETE_EVENT,
  
  ILLUSION_CREATE_EVENT_PARTICIPANT,
  ILLUSION_FIND_EVENT_PARTICIPANT,
  ILLUSION_UPDATE_EVENT_PARTICIPANT, 
  ILLUSION_DELETE_EVENT_PARTICIPANT,
  
  FORGE_COOPS_ACCESS_FILE,
  FORGE_COOPS_MODIFY_FILE, 

  USERS_CREATE,
  USERS_LIST, 
  USERS_ACCESS_ME, 
  
  SYSTEM_JPA_CACHE_FLUSH, 
  
}
