package fi.foyt.fni.rest.illusion;

public enum OAuthScopes {
  
  ILLUSION_LIST_EVENTS,
  ILLUSION_FIND_EVENT,
  ILLUSION_CREATE_EVENT,
  ILLUSION_UPDATE_EVENT,
  ILLUSION_DELETE_EVENT,
  
  FORGE_COOPS_ACCESS_FILE,
  FORGE_COOPS_MODIFY_FILE, 
  
  USERS_ACCESS_ME, 
  
  SYSTEM_JPA_CACHE_FLUSH

}
